# Generated by Django 2.1.2 on 2018-11-05 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invetory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('db3f6c41-d158-4068-8f26-ac8bf799b409'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('provider', models.CharField(max_length=256)),
                ('thc_percent', models.IntegerField()),
                ('cbd_percent', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
