# Generated by Django 2.1.3 on 2018-11-05 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('943f9962-fef0-4db5-937b-41c10bcff0d5'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('provider', models.CharField(max_length=256)),
                ('thc_percent', models.IntegerField()),
                ('cbd_percent', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Invetory',
        ),
    ]
