# Generated by Django 2.1.3 on 2018-11-05 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181105_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8fd6701-22b7-40ac-b1e1-1e56f77c6beb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
